## 3. 처음 시작하는 단위 테스트

---

제스트

- 테스트 프레임워크이자 테스트 러너
- 목 객체와 코드 커버리지 수집 기능
- 메타의 오픈소스

### 테스트 구성 요소

---

```tsx
// src/03/02/index.ts
export function add(a: number, b: number) {
  return a + b;
}

// src/03/02/index.text.ts
import { add } from "./";

test("add: 1 + 2는 3", () => {
  expect(add(1, 2)).toBe(3);
});
```

- 반드시 같은 폴더일 필요 없음. 보통 `__test__` 폴더에 많이 작성함
- `test(테스트명, 테스트 함수);`
  - 단언문 `expect(검증값).toBe(기댓값);`
  - 매처 `toBe(기댓값)`
- 테스트 그룹 `describe(그룹명, 그룹함수)`
  - 연관성 있는 테스트들을 그룹화하고 싶을 때
    ```tsx
    describe("add", () => {
      test("add: 1 + 1는 2", () => {
        expect(add(1, 1)).toBe(2);
      });
      test("add: 1 + 2는 3", () => {
        expect(add(1, 2)).toBe(3);
      });
    });
    ```
  - test는 중첩시킬 수 없지만 describe는 중첩 가능
    ```tsx
    describe("사칙 연산", () => {
    	describe("add", () => {
    		test(..., () => { expect(add(1, 1).toBe(2)); });
    		test(...);
    	});
    	describe("sub", () => {
    		test(..., () => { expect(sub(1, 1).toBe(0)); });
    		test(...);
    	});
    });
    ```

### 테스트 실행

---

1. 명령어로 실행
   - package.json 에 npm script 추가
     ```tsx
     {
     	"scripts": {
     		"test": "jest"
     	}
     }
     ```
   - `npm test` 프로젝트의 모든 테스트 코드 실행
   - `npm test '파일명'` 지정된 테스트 파일만 실행
     ![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/719ef110-29bc-4a6a-91c0-ea84d151d59b/1ce20217-7529-4d2a-9689-557acd75f96c/image.png)
     ![틀렸을 경우](https://prod-files-secure.s3.us-west-2.amazonaws.com/719ef110-29bc-4a6a-91c0-ea84d151d59b/87d9c667-c715-4175-ab91-a030ac3444af/image.png)
     틀렸을 경우
     → 테스트 코드, 테스트 대상에도 문제가 없는데 실패한다면? 버그가 있다는 의미
2. vscode 확장 프로그램 “제스트 러너” 사용

   ![코드 상단에 런 생김](https://prod-files-secure.s3.us-west-2.amazonaws.com/719ef110-29bc-4a6a-91c0-ea84d151d59b/843581e2-1777-4ee2-acae-1867e6770dca/image.png)

   코드 상단에 런 생김

### 조건 분기

---

- 상한이 있는 덧셈 함수 테스트 → 테스트명을 올바르게 짓자
  ```diff
  -test("70 + 80은 100", () => {
  +test("반환값의 상한은 '100'이다", () => {
  	expect(add(70, 80), 100);
  })
  ```

에지 케이스와 예외 처리

- 모듈에 예외처리를 해두었다면 “디버거” 로 문제를 빨리 발견하자
- `Type Annotation` 타입스크립트에서 함수의 매개변수에 Typing을 해 타입을 제한하는 것
  ```tsx
  export function add(a: number, b: number) { ... }

  add("1", "2"); // 타입 에러 발생
  ```
- 런타임에 예외 발생시키기
  ```tsx
  export function add(a: number, b: number) {
    if (a < 0 || a > 100) {
      throw new Error("0~100 사이의 값을 입력해주세요");
    }
  }
  ```
- 예외 발생 검증 테스트
  `expect(예외가 발생하는 함수).toThrow();`
  - 예외 발생함수가 예외를 발생시키는지 보려면 반드시 화살표 함수로 감싸야함!
  ```tsx
  expect(add(-10, 110)).toThrow(); // x
  expect(() => add(-10, 110)).toThrow(); // o
  ```
  ![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/719ef110-29bc-4a6a-91c0-ea84d151d59b/28485aca-ebe0-4e05-8923-6be539cd5aee/image.png)
  ![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/719ef110-29bc-4a6a-91c0-ea84d151d59b/8b48f1cf-418a-4722-a7b6-060328c3eb5f/image.png)
- 오류 메시지를 활용한 세부사항 검증
  `expect(예외 발생 함수).toThrow(throw된 메시지)`
  ![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/719ef110-29bc-4a6a-91c0-ea84d151d59b/77dc9cc8-fa26-4a5e-9f22-4938d2e8f707/image.png)
  ![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/719ef110-29bc-4a6a-91c0-ea84d151d59b/1d4fb52f-4ad4-4a30-93f4-65686d600032/image.png)
- instanceof 활용하기
  ```tsx
  export class RangeError extends Error {}

  function checkRange(value: number) {
    if (value < 0 || value > 100) {
      throw new RangeError("0~100 사이의 값을 입력해주세요");
    }
  }

  expect(() => add(110, -10)).toThrow(RangeError);
  ```
  ![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/719ef110-29bc-4a6a-91c0-ea84d151d59b/ff131649-08e2-4b10-a756-cb58beca800c/image.png)

### 용도별 매처

---

1. 진릿값 검증
   - `toBeTruthy` 참인지 검증. not으로 반전 가능
   - `toBeFalsy` 거짓인지 검증. not으로 반전 가능
   - `toBeNull` , `toBeUndefined` , `toBeNaN`
2. 수치 검증
   - `toEqual`, `toGreaterThan`, `toBeLessThan`
   - `toBeCloseTo(검증값, 자릿수)` 소수점 검증시(JS는 소수계산 오차가 있기 때문)
     ![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/719ef110-29bc-4a6a-91c0-ea84d151d59b/7cd101be-b33a-4b0a-942f-29230f999009/image.png)
     ```tsx
     test("소수 계산 시 지정한 자릿수까지 비교", () => {
       expect(0.1 + 0.2).toBeCloseTo(0.3);
       expect(0.1 + 0.2).toBeCloseTo(0.3, 15); // 여기까진 통과
       expect(0.1 + 0.2).toBeCloseTo(0.3, 16); // 미통과
     });
     ```
3. 문자열 검증(toBe, toEqual 포함)
   - `toContain` 일부 일치
   - `toMatch(정규 표현)` 정규식 일치
   - `toHaveLength` 문자열 길이
   - `stringContaining`, `stringMatching` 객체 프로퍼티 중 문자열 일부가 있으면 통과
     ```tsx
     const obj = { status: 200, message: "Hello World" };

     test("객체에 포함된 문자열 비교", () => {
       expect(obj).toEqual({
         status: 200,
         message:
           expect.stringContaining("World") || expect.stringMatching(/World/),
       });
     });
     ```
4. 배열 검증
   - `toContain` 특정 값이 포함되었는지, `toHaveLength` 배열 길이
   - `toContainEqual` 특정 객체가 포함되었는지
   - toEqual + `arrayContaining` 인수로 넘겨준 배열의 요소들이 전부 포함되었는지
     ```tsx
     const tags = ["Jest", "Storybook", "Playwright", "React", "Next.js"];
     const objs = [{ a: 1 }, { b: 1 }, { c: 2 }];
     test("원시값 배열 검증", () => {
       expect(tags).toContain("Jest");
       expect(tags).toHaveLength(5);
     });

     test("객체를 포함하는 배열", () => {
       expect(objs).toContainEqual({ a: 1 });
       expect(objs).toEqual(expect.arrayContaining([{ b: 1 }, { c: 1 }])); // 실패
     });
     ```
5. 객체 검증
   - `toMatchObject` 부분적으로 프로퍼티가 일치하면 성공
   - `toHaveProperty` 특정 프로퍼티가 있는지 검증
   - `objectContaining` 객체 내 또 다른 객체 검증
     ![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/719ef110-29bc-4a6a-91c0-ea84d151d59b/5314c2ab-7fb5-4bd3-a806-d079d6e4b79a/image.png)

### 비동기 처리 테스트

---

인수로 받은 대기 시간 만큼 기다리고, 경과 시간을 반환값으로 resolve하는 함수 wait 작성

```tsx
export function wait(duration: number) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(duration);
    }, duration);
  });
}
```

1. Promise 반환하는 작성법

   **promise를 리턴하면 promise가 처리 중인 작업이 완료될 때까지 테스트 판정을 유예한다.**

   ```tsx
   test("지정 시간을 기다린 뒤 경과 시간과 함께 resolve된다", () => {
     return wait(50).then((duration) => {
       expect(duration).toBe(50);
     });
   });
   ```

2. resolves 매처를 사용해 단언문을 반환

   ```tsx
   test("지정 시간을 기다린 뒤 경과 시간과 함께 resolve된다", () => {
     return expect(wait(50)).resolves.toBe(50);
   });
   ```

3. async/await를 활용한 작성법**\*\***

   ```tsx
   test("지정 시간을 기다린 뒤 경과 시간과 함께 resolve된다", async () => {
     await expect(wait(50)).resolves.toBe(50);
   });
   ```

4. Promise가 완료되는 것을 기다린 뒤 단언문 실행**\*\***

   ```tsx
   test("지정 시간을 기다린 뒤 경과 시간과 함께 resolve된다", async () => {
     expect(await wait(50)).toBe(50);
   });
   ```

   **→ 비동기 단언문이 여럿일 때 유용**

Reject 검증 테스트

```tsx
export function timeout(duration: number) {
  return new Promise((_, reject) => {
    setTimeout(() => {
      reject(duration);
    }, duration);
  });
}
```

1. Promise를 리턴 + catch에 단언문 작성

   ```tsx
   test("지정 시간을 기다린 뒤 경과 시간과 함께 reject된다", () => {
     return timeout(50).catch((duration) => {
       expect(duration).toBe(50);
     });
   });
   ```

2. rejects 매처 활용 + async/await

   ```tsx
   test("지정 시간을 기다린 뒤 경과 시간과 함께 reject된다", async () => {
     await expect(timeout(50)).rejects.toBe(50);
   });
   ```

3. try-catch 문 사용

   ```tsx
   test("지정 시간을 기다린 뒤 경과 시간과 함께 reject된다", async () => {
     expect.assertions(1); // Verifies that a certain number of assertions are called during a test. This is often useful when testing asynchronous code, in order to make sure that assertions in a callback actually got called.
     try {
       await timeout(50);
     } catch (err) {
       expect(err).toBe(50);
     }
   });
   ```

   - what is `expect.assertions(n)` ?
     단언문이 n번 실행되지 않으면 에러가 난다. 예를 들어 위 코드에서 timeout이 아니라 실수로 wait를 사용했을 경우 단언문에 도달하지 않음. 이를 위해서는 단언문이 몇번 실행되어야 하는지를 명시해주어야함
     ```tsx
     test("지정 시간을 기다린 뒤 경과 시간과 함께 reject된다", async () => {
       // expect.assertions(1);
       try {
         await wait(50);
       } catch (err) {
         expect(err).toBe(50); // 도달하지 않음
       }
     });
     ```
     ![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/719ef110-29bc-4a6a-91c0-ea84d151d59b/f4733b4a-0c31-4f73-afc6-df713fad532d/image.png)
     그냥 단언문이 몇번 실행될 것인지 jest에게 알려주는 용도 인듯
     ```tsx
     async function runOnceErrorAssertion(
       options: RunnerOptions,
       message: string
     ) {
       expect.assertions(1); // 한번만 시도
       try {
         await runOnce(options);
       } catch (e) {
         expect(e.message).toMatch(message);
       }
     }
     ```
     ![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/719ef110-29bc-4a6a-91c0-ea84d151d59b/b37a8f63-83b9-40fc-9476-9d5a164fbde0/image.png)

<aside>
❓

다음 테스트 코드를 올바르게 고쳐보자

```tsx
test("지정 시간을 기다린 뒤 경과 시간과 함께 reject된다", () => {
  expect(wait(2000)).resolves.toBe(3000);
});
```

- 정답
  문제: 2000을 반환해서 실패할 것 같지만, 실제로는 통과. promise를 리턴하고 있지 않아서 jest가 안기다려줌!
  `return expect(wait(2000)).resolves.toBe(3000);`
  테스트함수가 동기함수이면 반드시 단언문을 return 해야함

</aside>

다음 원칙을 따르면 위와 같은 실수 줄일 수 있음

- 비동기 처리 시에는 반드시 async 함수로 작성
- .resolves, .rejects 단언문은 반드시 await
- try-catch 사용시에는 expect.assertions 한다
